### ISSUE TITLE
new lib file

### ISSUE THREAD

**Issue by KakCAT** [RobertFoll/RevMob-Xamarin-iOS#1]
Hi, 

how can I get a new libRevMobAds.a for the updated revmob library? I'd like to integrate the latest version but there's no such .a file in the latest revmob package.

thanks!

**Comment by RobertFoll** [comment]
Hi,

You just need to copy and rename "RevMobAds.framework/Versions/A/RevMobAds" from the latest iOS SDK to libRevMobAds.a which is a Xamarin naming convention.  I hope that helps!

Rob

FYI - I've been meaning to update this project with the latest revmob library.  I'll try to get this done soon.

**Comment by KakCAT** [comment]
Hi!

just two points:

I just did a binary file compare between the latest revmob library and the one used by this binding and they're identical. At least today (2015/12/28) the binding is up-to-date

For some reason I was receiving an undefined reference when compiling my project (and also the sample). Adding CoreLocation to ...linkWith.cs fixed the problem

**Comment by RobertFoll** [comment]
Great!  FYI - I just added a new repository project which is a binding for the Heyzap SDK, which supports multiple ad networks in case you are interested.
